### PR TITLE
Feat/dark mode toggle added

### PR DESCRIPTION
**Pull request by GD0910**
Added dark theme toggle button 
resolve issue #7 

working Video : 

https://github.com/nishaaannnt/advance-bookmarks/assets/88530462/5a48335a-5208-413f-ba0e-feed5b8a4d34

### CODE REVIEW

**Comment by nishaaannnt** [comment]
@GD0910 
1. why is the Coffee button redirecting to a random persons donate section ? We dont need to make that button functional yet.
2. After reopening the extension default dark mode is enabled. To solve this try to understand and see the localstorage methods.

Also update your branch as new changes are pushed
Please dont add unnecessary changes. I am ignoring it as this is your first contribution but please look into above issues.

**Comment by GD0910** [comment]
> @GD0910
> 
> 1. why is the Coffee button redirecting to a random persons donate section ? We dont need to make that button functional yet.
> 2. After reopening the extension default dark mode is enabled. To solve this try to understand and see the localstorage methods.
> 
> Also update your branch as new changes are pushed Please dont add unnecessary changes. I am ignoring it as this is your first contribution but please look into above issues.

Ok sorry for point 1 mistake I will correct it and push it immediate 
2nd I will try the localStorage method

**Comment by GD0910** [comment]
Implemented theme colour according to system mode
Video :

https://github.com/nishaaannnt/advance-bookmarks/assets/88530462/af1b8183-fb11-4678-ab72-03b3d47b4c9e

I any changes please infrom me and Thank you @nishaaannnt  for another chance same mistake wort be repeated

**Review by nishaaannnt — APPROVED** [review]
lgtm

**Pull request merged**
