### PR TITLE
Configure `Watch Changes` Library During Development

### PR DESCRIPTION
**Pull request by ArkadiK94**
What: Install npm-watch and add relevant script and configuration.
Why: Make it easier for developers to make changes
resolve issue #10 

Note, I didn't add the line in the CONTRIBUTING.md about refreshing the extension because I saw that we don't need it. It refreshes automatically.

### CODE REVIEW

**Review by nishaaannnt — APPROVED** [review]
lgtm 
thanks @ArkadiK94

**Comment by ArkadiK94** [comment]
Hi, I looked it up a little more. I saw that there are preferred ways to accomplish the watching mode. We should choose a module bundler. There a many options: webpack, vite, parcel, and rollup. I saw a lot of recommendations to use vite (with crxjs.dev plug-in, if needed). What are your thoughts about it? Do you have a preference?

**Comment by ArkadiK94** [comment]
@nishaaannnt

**Comment by ArkadiK94** [comment]
Do you want me to open a new issue about it or can you reopen the old issue? 
Or leave it as it is for now?

**Comment by nishaaannnt** [comment]
Hello @ArkadiK94 i guess currently its better to leave it as it is for.
If i reconsider my decision i will let you know.
Thank you !

**Pull request merged**
